site_name: Ohana-Cloud.com Docs
site_url: https://docs.ohana-cloud.com
nav:
  - Home: home.md
  - Blue Teaming:
    - blue/blueteaming.md
    - Network Tools:
        - Snort IDS/IPS: blue/tools-network/snort.md
        - Zeek Traffic Analyser: blue/tools-network/zeek.md
        - NetworkMiner: blue/tools-network/NetworkMiner.md
    - AI Security:
        - AI Security Tools: ai/tools-ai.md
    - Blue Teaming Resources: blue/resources.md
  - Servers:
    - Linux:
      - AlmaLinux Setup Guide: servers/linux/almalinux_setup.md
      - Basic Commands: servers/linux/commands.md
    - Firewalld Basics: servers/firewalld.md
    - SELinux Basics: servers/SELinux.md
  - Applications:
    - MkDocs: servers/applications/mkdocs_setup.md
  - About me: about.md


theme:
  name: material
  features:
    - search.suggest
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    annotation: material/chevron-right-circle

extra:
  social:
    - icon: material/github
      link: https://github.com/PhilT95/docs
    - icon: material/linkedin
      link: https://www.linkedin.com/in/phil-trommer/
  generator: false
copyright: Copyright &copy; 2025 Phil Trommer

  


plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 
