site_name: athenlyx.com
site_url: https://athenlyx.com
repo_url: https://github.com/PhilT95/athenlyx
repo_name: PhilT95/athenlyx

nav:
  - Home: index.md
  - Linux Administration:
    - AlmaLinux: 
      - AlmaLinux Setup Guide: linux-admin/rhel-alma/almalinux_setup.md
      - firewalld basics: linux-admin/rhel-alma/firewalld.md
      - SELinux basics: linux-admin/rhel-alma/SELinux.md
      - Command Cheat Sheet: linux-admin/rhel-alma/commands.md
    - Ansible:
      - linux-admin/ansible/index.md
  - Security - Blue Teaming:
    - blue-sec/index.md
    - Network Security:
      - blue-sec/network-sec/index.md
      - Snort IDS/IPS: blue-sec/network-sec/snort.md
      - Zeek Traffic Analyzer: blue-sec/network-sec/zeek.md
      - Wireshark:
        - blue-sec/network-sec/wireshark/index.md
        - Wireshark Advanced Features: blue-sec/network-sec/wireshark/wireshark_advanced.md
        - Wireshark Traffic Analysis: blue-sec/network-sec/wireshark/wireshark_trafficanalysis.md
      - TShark:
        - blue-sec/network-sec/tshark/index.md
        - TShark CLI: blue-sec/network-sec/tshark/tshark_cli_wireshark.md
      - NetworkMiner: blue-sec/network-sec/NetworkMiner.md
      - BRIM: blue-sec/network-sec/brim.md
    - Endpoint Security:
      - blue-sec/endpoint-sec/index.md
      - Windows Security:
        - blue-sec/endpoint-sec/windows/index.md
        - Windows Core Services: blue-sec/endpoint-sec/windows/core_windows_processes.md
        - Sysinternals: blue-sec/endpoint-sec/windows/sysinternals.md
        - Windows Event Log: blue-sec/endpoint-sec/windows/windows_event_logs.md
        - Sysmon: blue-sec/endpoint-sec/windows/sysmon.md
        - OSquery: blue-sec/endpoint-sec/windows/osquery.md
    - Web Security:
      - SafeLine WAF:
        - blue-sec/web-sec/safeline/index.md
    - SIEM:
      - blue-sec/siem/index.md
      - Elastic: blue-sec/siem/elastic.md
      - Splunk: blue-sec/siem/splunk.md
      - Wazuh:
        - blue-sec/siem/wazuh/index.md
        - Wazuh Setup: blue-sec/siem/wazuh/wazuh_setup.md
        - Wazuh Log Collection: blue-sec/siem/wazuh/log_collecting.md
    - Security Assessment:
      - blue-sec/security-assessment/index.md
      - OpenSCAP: blue-sec/security-assessment/openscap.md
    - DFIR: 
      - blue-sec/dfir/index.md
    - Resources: blue-sec/resources.md
  - Self-Hosted Apps & Services:
    - services/index.md
    - MkDocs:
      - services/mkdocs/index.md
      - MkDocs Setup: services/mkdocs/mkdocs_setup.md
      - MkDocs Auto-Update: services/mkdocs/mkdocs_autoupdate.md
  - AI:
    - AI Tools Cheat Sheet: ai/tools-ai.md
  - About me:
    - about/index.md



theme:
  name: material
  custom_dir: overrides
  features:
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - announce.dismiss
  language: en
  logo: assets/icon_round.png
  favicon: assets/icon_round.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    annotation: material/chevron-right-circle
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: material/github
      link: https://github.com/PhilT95/docs
    - icon: material/linkedin
      link: https://www.linkedin.com/in/phil-trommer/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/philadelphia95.bsky.social
    - icon: material/mail
      link: mailto:docs@s-guard.simplelogin.com

  generator: false
copyright: Copyright &copy; 2025 AthenlyX

extra_css:
  - stylesheets/extra.css


  


plugins:
  - search
  - social
  - privacy
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      zoomable: true
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      caption_position: bottom
      auto_themed: true
      auto_caption: true
      shadow: true
      manual: false
      slide_effect: slide

  - git-revision-date-localized:
      enable_creation_date: true


markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - def_list
  - admonition
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append: ["includes/abbreviations.md"]
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
  - pymdownx.keys

watch:
  - includes
