site_name: athenlyx.com
site_url: https://athenlyx.com
repo_url: https://github.com/PhilT95/athenlyx
repo_name: PhilT95/athenlyx
nav:
  - Home: index.md
  - Blue Teaming:
    - blue/index.md
    - Network Tools:
        - blue/tools-network/index.md
        - Snort IDS/IPS: blue/tools-network/snort.md
        - Zeek Traffic Analyzer: blue/tools-network/zeek.md      
        - Wireshark:
          - blue/tools-network/wireshark/index.md
          - Wireshark Advanced Features: blue/tools-network/wireshark/wireshark_advanced.md
          - Wireshark Traffic Analysis: blue/tools-network/wireshark/wireshark_trafficanalysis.md
        - TShark:
          - blue/tools-network/tshark/index.md
          - TShark CLI: blue/tools-network/tshark/tshark_cli_wireshark.md
        - NetworkMiner: blue/tools-network/NetworkMiner.md
        - BRIM: blue/tools-network/brim.md
    - Endpoint Security:
        - blue/endpoint-security/index.md
        - Windows Security:
          - blue/endpoint-security/windows/index.md
          - Windows Core Services: blue/endpoint-security/windows/core_windows_processes.md
          - Sysinternals: blue/endpoint-security/windows/sysinternals.md
          - Windows Event Logs: blue/endpoint-security/windows/windows_event_logs.md
          - Sysmon: blue/endpoint-security/windows/sysmon.md
          - OSquery: blue/endpoint-security/windows/osquery.md
    - AI Security:
        - AI Security Tools: ai/tools-ai.md
    - Blue Teaming Resources: blue/resources.md
  - Servers:
    - Linux:
      - AlmaLinux Setup Guide: servers/linux/almalinux_setup.md
      - Basic Commands: servers/linux/commands.md
      - Hardening:
        - servers/linux/hardening/index.md
        - OpenSCAP: servers/linux/hardening/openscap.md
    - Firewalld Basics: servers/firewalld.md
    - SELinux Basics: servers/SELinux.md
  - Applications:
    - applications/index.md
    - MkDocs:
      - applications/mkdocs/index.md
      - MkDocs Setup : applications/mkdocs/mkdocs_setup.md
      - MkDocs Auto-Update : applications/mkdocs/mkdocs_autoupdate.md
    - SafeLine:
      - applications/safeline/index.md
  - About me: about/index.md


theme:
  name: material
  features:
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - announce.dismiss
  language: en
  logo: assets/icon_round.png
  favicon: assets/icon_round.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    annotation: material/chevron-right-circle
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: material/github
      link: https://github.com/PhilT95/docs
    - icon: material/linkedin
      link: https://www.linkedin.com/in/phil-trommer/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/philadelphia95.bsky.social
    - icon: material/mail
      link: mailto:docs@s-guard.simplelogin.com

  generator: false
copyright: Copyright &copy; 2025 AthenlyX

extra_css:
  - stylesheets/extra.css


  


plugins:
  - search
  - social
  - privacy
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      zoomable: true
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      caption_position: bottom
      auto_themed: true
      auto_caption: true
      shadow: true
      manual: false
      slide_effect: slide

  - git-revision-date-localized:
      enable_creation_date: true


markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - def_list
  - admonition
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append: ["includes/abbreviations.md"]
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
  - pymdownx.keys

watch:
  - includes
